# Generated by Django 5.2 on 2025-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='image',
            field=models.ImageField(default='1', upload_to='images/'),
            preserve_default=False,
        ),
    ]
