# Generated by Django 5.2 on 2025-06-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_materials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
