# Generated by Django 5.2 on 2025-06-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_materials_download_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='download_count',
            new_name='views',
        ),
    ]
