# Generated by Django 5.2 on 2025-06-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_rename_download_count_materials_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mysite.subjects'),
            preserve_default=False,
        ),
    ]
