# Generated by Django 5.2 on 2025-06-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_teacherresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherresource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teacherresource',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='content_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
