# Generated by Django 5.2.4 on 2025-07-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learninghub.subject'),
            preserve_default=False,
        ),
    ]
