# Generated by Django 5.2 on 2025-08-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learninghub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="subject_image",
            field=models.ImageField(null=True, upload_to="subjects_image"),
        ),
    ]
