# Generated by Django 5.2 on 2025-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learninghub", "0002_subject_subject_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
