# Generated by Django 5.2.4 on 2025-07-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0002_remove_material_subtopic_material_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.AddField(
            model_name='material',
            name='subtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learninghub.subtopic'),
            preserve_default=False,
        ),
    ]
