# Generated by Django 5.2.4 on 2025-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0003_remove_material_subject_material_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='html_content',
            field=models.TextField(),
        ),
    ]
