# Generated by Django 5.2 on 2025-08-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learninghub", "0003_subject_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="topic_image",
            field=models.ImageField(null=True, upload_to="topic_images"),
        ),
    ]
