# Generated by Django 5.2 on 2025-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0004_alter_material_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
