# Generated by Django 5.2 on 2025-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0004_user_language_assignmentsubmission_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
