# Generated by Django 5.2.5 on 2025-08-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0004_topic_description_topic_topic_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together={('student', 'badge')},
        ),
    ]
