# Generated by Django 5.2.5 on 2025-08-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learninghub', '0005_alter_studentbadge_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['order', 'id']},
        ),
    ]
